;; ============================================================
;; CLBC reference VM (v1)
;; - Deterministic execution (parse+trace)
;; - Produces transcript hash as sha256(canonical transcript bytes)
;; ============================================================

(define (vm-dirname path)
  (let loop ((i (- (string-length path) 1)))
    (if (< i 0) "."
        (if (char=? (string-ref path i) #\/)
            (if (= i 0) "/" (substring path 0 i))
            (loop (- i 1))))))

(define (vm-load-relative rel)
  (let* ((cf (current-filename))
         (base (if (and cf (string? cf)) (vm-dirname cf) (getcwd))))
    (load (string-append base "/" rel))))

(vm-load-relative "../clbc/format.scm")
(vm-load-relative "../clbc/opcodes.scm")
(vm-load-relative "../nrr/hash.scm")

(use-modules (rnrs io ports))

(define (take-bytes xs n)
  (let loop ((i 0) (ys xs) (out '()))
    (if (= i n)
        (reverse out)
        (if (null? ys)
            (error "take-bytes: truncated" n)
            (loop (+ i 1) (cdr ys) (cons (car ys) out))))))

(define (drop-bytes xs n)
  (if (<= n 0) xs
      (if (null? xs) '()
          (drop-bytes (cdr xs) (- n 1)))))

(define (consume-uleb rs idx)
  ;; returns (value . new-idx)
  (let* ((p (uleb128-decode (drop-bytes rs idx)))
         (v (car p))
         (rest (cdr p))
         (consumed (- (length (drop-bytes rs idx)) (length rest))))
    (cons v (+ idx consumed))))

(define (consume-n rs idx n)
  ;; returns (bytes . new-idx)
  (cons (take-bytes (drop-bytes rs idx) n) (+ idx n)))

(define (consume-value-payload rs idx vtype)
  ;; returns (payload-bytes . new-idx) including any length prefix bytes when applicable
  (cond
   ((= vtype 0) (cons '() idx))
   ((= vtype 1) (consume-n rs idx 1))
   ((= vtype 3)
    (let* ((p (consume-uleb rs idx))
           (n (car p))
           (idx2 (cdr p)))
      (cons (uleb128-encode n) idx2)))
   ((= vtype 4)
    (let* ((p (consume-uleb rs idx))
           (sid (car p))
           (idx2 (cdr p)))
      (cons (uleb128-encode sid) idx2)))
   ((= vtype 5)
    (let* ((p (consume-uleb rs idx))
           (n (car p))
           (idx2 (cdr p))
           (q (consume-n rs idx2 n)))
      (cons (bytes-append (uleb128-encode n) (car q)) (cdr q))))
   ((= vtype 6) (consume-n rs idx 4))
   (else
    (cons '() idx))))

(define (vm-run-clbc-bytes clbc-bytes)
  ;; returns alist: '((ok? . bool) (transcript-hash . string) (events . n) (errors . (..)))
  (let* ((decoded (clbc-decode clbc-bytes))
         (rs (cdr (assq 'record-stream decoded)))
         (errors '())
         (events 0)
         (transcript '())
         (idx 0))

    (define (fail msg)
      (set! errors (cons msg errors)))

    (define (emit chunk)
      (set! events (+ events 1))
      (set! transcript (bytes-append transcript chunk)))

    (let loop ()
      (if (>= idx (length rs))
          `((ok? . ,(null? errors))
            (transcript-hash . ,(hash-content transcript))
            (events . ,events)
            (errors . ,(reverse errors)))
          (let ((op (list-ref rs idx)))
            (cond
             ;; framing
             ((= op OP_BEGIN_RECORD)
              (let* ((q (consume-n rs idx 2))
                     (hdr (car q))
                     (idx2 (cdr q))
                     (p (consume-uleb rs idx2))
                     (phase (car p))
                     (idx3 (cdr p)))
                (set! idx idx3)
                (emit (bytes-append hdr (uleb128-encode phase)))
                (loop)))
             ((= op OP_END_RECORD)
              (let ((q (consume-n rs idx 1)))
                (set! idx (cdr q))
                (emit (car q))
                (loop)))

             ;; validation
             ((= op OP_CHECKS)
              (let* ((q (consume-n rs idx 1))
                     (idx2 (cdr q))
                     (p (consume-uleb rs idx2))
                     (n (car p))
                     (idx3 (cdr p))
                     (r (consume-n rs idx3 n))
                     (ids (car r))
                     (idx4 (cdr r)))
                (set! idx idx4)
                (emit (bytes-append (list OP_CHECKS) (uleb128-encode n) ids))
                (loop)))
             ((= op OP_RESULT)
              (let ((q (consume-n rs idx 2)))
                (set! idx (cdr q))
                (emit (car q))
                (loop)))
             ((= op OP_HASH)
              (let* ((q (consume-n rs idx 1))
                     (idx2 (cdr q))
                     (p (consume-uleb rs idx2))
                     (sid (car p))
                     (idx3 (cdr p)))
                (set! idx idx3)
                (emit (bytes-append (list OP_HASH) (uleb128-encode sid)))
                (loop)))

             ;; context
             ((= op OP_CTX_BEGIN)
              (let* ((q (consume-n rs idx 1))
                     (idx2 (cdr q))
                     (p (consume-uleb rs idx2))
                     (cid (car p))
                     (idx3 (cdr p)))
                (set! idx idx3)
                (emit (bytes-append (list OP_CTX_BEGIN) (uleb128-encode cid)))
                (loop)))
             ((= op OP_CTX_META)
              (let* ((q (consume-n rs idx 1))
                     (idx2 (cdr q))
                     (p (consume-uleb rs idx2))
                     (complexity (car p))
                     (idx3 (cdr p))
                     (shape (list-ref rs idx3))
                     (idx4 (+ idx3 1)))
                (set! idx idx4)
                (emit (bytes-append (list OP_CTX_META) (uleb128-encode complexity) (list shape)))
                (loop)))
             ((= op OP_VTX_DEF)
              (let* ((q (consume-n rs idx 1))
                     (idx2 (cdr q))
                     (p (consume-uleb rs idx2))
                     (vid (car p))
                     (idx3 (cdr p))
                     (role (list-ref rs idx3))
                     (basis (list-ref rs (+ idx3 1)))
                     (optional (list-ref rs (+ idx3 2)))
                     (vtype (list-ref rs (+ idx3 3)))
                     (idx4 (+ idx3 4))
                     (vp (consume-value-payload rs idx4 vtype))
                     (payload (car vp))
                     (idx5 (cdr vp)))
                (set! idx idx5)
                (emit (bytes-append (list OP_VTX_DEF) (uleb128-encode vid) (list role basis optional vtype) payload))
                (loop)))
             ((= op OP_EDGE_DEF)
              (let* ((q (consume-n rs idx 1))
                     (idx2 (cdr q))
                     (p1 (consume-uleb rs idx2)) (from (car p1)) (idx3 (cdr p1))
                     (p2 (consume-uleb rs idx3)) (to (car p2)) (idx4 (cdr p2))
                     (p3 (consume-uleb rs idx4)) (sid (car p3)) (idx5 (cdr p3))
                     (wtype (list-ref rs idx5))
                     (idx6 (+ idx5 1))
                     (wp (consume-value-payload rs idx6 wtype))
                     (wpayload (car wp))
                     (idx7 (cdr wp)))
                (set! idx idx7)
                (emit (bytes-append (list OP_EDGE_DEF) (uleb128-encode from) (uleb128-encode to) (uleb128-encode sid) (list wtype) wpayload))
                (loop)))
             ((= op OP_FACE_DEF)
              (let* ((q (consume-n rs idx 1))
                     (idx2 (cdr q))
                     (p1 (consume-uleb rs idx2)) (a (car p1)) (idx3 (cdr p1))
                     (p2 (consume-uleb rs idx3)) (b (car p2)) (idx4 (cdr p2))
                     (p3 (consume-uleb rs idx4)) (c (car p3)) (idx5 (cdr p3))
                     (p4 (consume-uleb rs idx5)) (sid (car p4)) (idx6 (cdr p4)))
                (set! idx idx6)
                (emit (bytes-append (list OP_FACE_DEF) (uleb128-encode a) (uleb128-encode b) (uleb128-encode c) (uleb128-encode sid)))
                (loop)))
             ((= op OP_KEY_DEF)
              (let* ((q (consume-n rs idx 1))
                     (idx2 (cdr q))
                     (p (consume-uleb rs idx2)) (kid (car p)) (idx3 (cdr p))
                     (auth (list-ref rs idx3))
                     (mut (list-ref rs (+ idx3 1)))
                     (idx4 (+ idx3 2)))
                (set! idx idx4)
                (emit (bytes-append (list OP_KEY_DEF) (uleb128-encode kid) (list auth mut)))
                (loop)))
             ((= op OP_CTX_END)
              (let ((q (consume-n rs idx 1)))
                (set! idx (cdr q))
                (emit (car q))
                (loop)))

             ;; transition
             ((= op OP_APPLY_BEGIN)
              (let ((q (consume-n rs idx 2)))
                (set! idx (cdr q))
                (emit (car q))
                (loop)))
             ((= op OP_APPLY_COEFF_REF)
              (let* ((q (consume-n rs idx 1))
                     (idx2 (cdr q))
                     (p (consume-uleb rs idx2))
                     (sid (car p))
                     (idx3 (cdr p)))
                (set! idx idx3)
                (emit (bytes-append (list OP_APPLY_COEFF_REF) (uleb128-encode sid)))
                (loop)))
             ((= op OP_APPLY_VARS)
              (let* ((q (consume-n rs idx 1))
                     (idx2 (cdr q))
                     (p (consume-uleb rs idx2))
                     (n (car p))
                     (idx3 (cdr p)))
                (let loopv ((i 0) (idxv idx3) (payload (bytes-append (list OP_APPLY_VARS) (uleb128-encode n))))
                  (if (= i n)
                      (begin
                        (set! idx idxv)
                        (emit payload)
                        (loop))
                      (let* ((pp (consume-uleb rs idxv))
                             (vid (car pp))
                             (idxn (cdr pp)))
                        (loopv (+ i 1) idxn (bytes-append payload (uleb128-encode vid))))))))
             ((= op OP_APPLY_OUT)
              (let* ((q (consume-n rs idx 1))
                     (idx2 (cdr q))
                     (p (consume-uleb rs idx2))
                     (vid (car p))
                     (idx3 (cdr p)))
                (set! idx idx3)
                (emit (bytes-append (list OP_APPLY_OUT) (uleb128-encode vid)))
                (loop)))
             ((= op OP_APPLY_END)
              (let ((q (consume-n rs idx 1)))
                (set! idx (cdr q))
                (emit (car q))
                (loop)))

             ;; projection
             ((= op OP_PROJ_BEGIN)
              (let ((q (consume-n rs idx 2)))
                (set! idx (cdr q))
                (emit (car q))
                (loop)))
             ((= op OP_PROJ_INPUT)
              (let* ((q (consume-n rs idx 1))
                     (idx2 (cdr q))
                     (p (consume-uleb rs idx2))
                     (cid (car p))
                     (idx3 (cdr p)))
                (set! idx idx3)
                (emit (bytes-append (list OP_PROJ_INPUT) (uleb128-encode cid)))
                (loop)))
             ((= op OP_PROJ_POINTS)
              (let* ((q (consume-n rs idx 1))
                     (idx2 (cdr q))
                     (p (consume-uleb rs idx2))
                     (n (car p))
                     (idx3 (cdr p))
                     (r (consume-n rs idx3 n))
                     (pts (car r))
                     (idx4 (cdr r)))
                (set! idx idx4)
                (emit (bytes-append (list OP_PROJ_POINTS) (uleb128-encode n) pts))
                (loop)))
             ((= op OP_PROJ_LINES)
              (let* ((q (consume-n rs idx 1))
                     (idx2 (cdr q))
                     (p (consume-uleb rs idx2))
                     (n (car p))
                     (idx3 (cdr p))
                     (r (consume-n rs idx3 (* n 3)))
                     (triples (car r))
                     (idx4 (cdr r)))
                (set! idx idx4)
                (emit (bytes-append (list OP_PROJ_LINES) (uleb128-encode n) triples))
                (loop)))
             ((= op OP_PROJ_END)
              (let ((q (consume-n rs idx 1)))
                (set! idx (cdr q))
                (emit (car q))
                (loop)))

             ;; commit
             ((= op OP_COMMIT)
              (let* ((q (consume-n rs idx 1))
                     (idx2 (cdr q))
                     (p1 (consume-uleb rs idx2)) (sid1 (car p1)) (idx3 (cdr p1))
                     (p2 (consume-uleb rs idx3)) (sid2 (car p2)) (idx4 (cdr p2))
                     (p3 (consume-uleb rs idx4)) (sid3 (car p3)) (idx5 (cdr p3))
                     (tsp (consume-n rs idx5 8))
                     (ts (car tsp))
                     (idx6 (cdr tsp)))
                (set! idx idx6)
                (emit (bytes-append (list OP_COMMIT)
                                    (uleb128-encode sid1) (uleb128-encode sid2) (uleb128-encode sid3)
                                    ts))
                (loop)))

             (#t
              (fail (string-append "unknown opcode: " (number->string op)))
              `((ok? . #f)
                (transcript-hash . ,(hash-content transcript))
                (events . ,events)
                (errors . ,(reverse errors))))))))))

(define (read-file-bytes path)
  (call-with-input-file path
    (lambda (port)
      (let loop ((out '()))
        (let ((b (get-u8 port)))
          (if (eof-object? b)
              (reverse out)
              (loop (cons b out))))))))
