input {
  # Accept logs from BICF services
  tcp {
    port => 5044
    codec => json
  }
}

filter {
  if [service] == "bicf-production" {
    mutate {
      add_field => { "module" => "production" }
    }
  }
  
  if [service] == "canvasl-interpreter" {
    mutate {
      add_field => { "module" => "canvasl" }
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "bicf-logs-%{+YYYY.MM.dd}"
  }
  
  stdout {
    codec => rubydebug
  }
}

