idf_component_register(
    SRCS
        "main.c"
        "wifi_mqtt.c"
        "clbc_vm.c"
        "udp_discovery.c"
        "../../canisa-mvp/canisa_mvp.c"
        "../../canisa-mvp/canisa_poly_f2.c"
        "../../canisa-mvp/sha256.c"
    INCLUDE_DIRS
        "."
        "../../canisa-mvp"
    REQUIRES
        nvs_flash
        esp_wifi
        esp_netif
        esp_event
        mqtt
        mbedtls
        json
)
