#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"

PORT="${PORT:-}"
BAUD="${BAUD:-115200}"
DEVICE_ID="${DEVICE_ID:-esp32-a}"

# Allow passing env-style KEY=VALUE args (common copy/paste mistake).
for arg in "$@"; do
  case "$arg" in
    PORT=*) PORT="${arg#PORT=}" ;;
    BAUD=*) BAUD="${arg#BAUD=}" ;;
    DEVICE_ID=*) DEVICE_ID="${arg#DEVICE_ID=}" ;;
    WIFI_SSID=*) WIFI_SSID="${arg#WIFI_SSID=}" ;;
    WIFI_PASSWORD=*) WIFI_PASSWORD="${arg#WIFI_PASSWORD=}" ;;
    MQTT_BROKER_HOST=*) MQTT_BROKER_HOST="${arg#MQTT_BROKER_HOST=}" ;;
    MQTT_BROKER_PORT=*) MQTT_BROKER_PORT="${arg#MQTT_BROKER_PORT=}" ;;
    *) ;;
  esac
done

if [ -z "$PORT" ]; then
  cat >&2 <<'EOF'
usage:
  PORT=/dev/ttyUSB0 DEVICE_ID=esp32-a WIFI_SSID='...' WIFI_PASSWORD='...' ./scripts/flash-esp32-mqtt-clbc.sh

also accepted (KEY=VALUE args):
  ./scripts/flash-esp32-mqtt-clbc.sh PORT=/dev/ttyUSB0 DEVICE_ID=esp32-a WIFI_SSID='...' WIFI_PASSWORD='...'

optional:
  MQTT_BROKER_HOST=gateway   # or an IP/hostname
  MQTT_BROKER_PORT=1883
  BAUD=115200
EOF
  exit 2
fi

WIFI_SSID="${WIFI_SSID:-}"
WIFI_PASSWORD="${WIFI_PASSWORD:-}"
MQTT_BROKER_HOST="${MQTT_BROKER_HOST:-gateway}"
MQTT_BROKER_PORT="${MQTT_BROKER_PORT:-1883}"

cd "$ROOT/embedded/esp32-mqtt-clbc"

if [ -n "$WIFI_SSID" ] && [ -n "$WIFI_PASSWORD" ]; then
  cat > main/config_local.h <<EOF
#pragma once
// Auto-generated by scripts/flash-esp32-mqtt-clbc.sh (this file is ignored by git).

#undef WIFI_SSID
#undef WIFI_PASSWORD
#undef MQTT_BROKER_HOST
#undef MQTT_BROKER_PORT
#undef DEVICE_ID

#define WIFI_SSID "$WIFI_SSID"
#define WIFI_PASSWORD "$WIFI_PASSWORD"
#define MQTT_BROKER_HOST "$MQTT_BROKER_HOST"
#define MQTT_BROKER_PORT $MQTT_BROKER_PORT
#define DEVICE_ID "$DEVICE_ID"
EOF
else
  echo "warn: WIFI_SSID/WIFI_PASSWORD not set; edit embedded/esp32-mqtt-clbc/main/config_local.h manually" >&2
fi

source "$ROOT/esp-idf/export.sh" >/dev/null
idf.py -p "$PORT" -b "$BAUD" build flash
